CREATE TABLE ExtraAccounts (
	id BIGINT(20) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    accName VARCHAR(50) NOT NULL,
    fk_spieler BIGINT(20) UNSIGNED,
    FOREIGN KEY (fk_spieler)
		REFERENCES spieler (id)
        ON UPDATE CASCADE ON DELETE CASCADE
);